swiftmailer:
      spool:     { type: memory }
      transport: smtp
      host:      smtp.mailtrap.io
      username:  47bf98ff84f3db
      password:  3600baecb9a3dd
      auth_mode: cram-md5
      port: 2525
